apiVersion: apps/v1
kind: Deployment
metadata:
  name: webpage-comparator
spec:
  replicas: 2
  selector:
    matchLabels:
      app: webpage-comparator
  template:
    metadata:
      labels:
        app: webpage-comparator
    spec:
      containers:
      - name: webpage-comparator
        image: gcr.io/web-comparision-tool/project_app
        ports:
        - containerPort: 8501
        
 